NP_API_URL:
NP_ADMIN_URL:
NP_AUTH_PUBLIC_URL:
NP_OAUTH_AUTH_URL:
NP_OAUTH_TOKEN_URL:
NP_OAUTH_LOGOUT_URL:
NP_OAUTH_CLIENT_ID:
NP_OAUTH_AUDIENCE:
NP_OAUTH_SUCCESS_REDIRECT_URL:
NP_OAUTH_HEADLESS_CALLBACK_URL:
NP_PLATFORM_CONFIG_URI: http://platformconfig:8080/api/v1
NP_ENFORCER_PLATFORM_API_URL: http://localhost:8080/api/v1
NP_ENFORCER_RETENTION_DELAY_DAYS:
NP_CORS_ORIGINS:

image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

platform:
  token: {}

jobPriorityClass:
  enabled: false

postgres:
  dsn: {}

postgres-db-init:
  image:
    repository: $DOCKER_SERVER/bitnami/postgresql

  adminDsn: {}
  migrationsRunnerDsn: {}
  serviceDsn: {}

  migrations:
    enabled: true

    image:
      repository: "$IMAGE_REPO"
      tag: "$IMAGE_TAG"

    command: ["alembic", "upgrade", "head"]

resources:
  requests:
    cpu: "1"
    memory: "1Gi"

ingress:
  enabled: false

secrets: []

zipkin: {}

sentry: {}
